### PR TITLE
feat: add comments count sorts on proposals list

### PR DESCRIPTION
**Pull request by jgrenat**
Hello,
This PR is for the sort options :)

### CODE REVIEW

**Comment by jgrenat** [comment]
Rebased on main after the merge of the previous PR

**Review by bpetetot — APPROVED** [review]

**Comment by bpetetot** [comment]
Great job 👍 Thanks!

**Comment by bpetetot** [comment]
@jgrenat Both PRs are deployed in production ;)

**Comment by jgrenat** [comment]
@bpetetot Awesome, thanks for all your work!

**Pull request merged**
